### ISSUE TITLE
Dissapearing projected shadows

### ISSUE THREAD

**Issue by SerGhost1915** [GTAmodding/GTAIV-Issues-List#149]
When I put the mod, all the shadows projected by cars lights dissapears

I use the latest version of the mod with various fixes and console visual.
I know the issue is with this mod because I use it alone and the problem persist

My config
i7-8550U
8gb RAM
Intel UHD 620 1gb VRAM

**Comment by RecklessGlue540** [comment]
This list is not for FusionFix stuff, it's for reporting the vanilla game's issues.

FusionFix comes by default set with Console Shadows On, and that gets rid of headlight shadows, because vehicle shadows under lights and headlight shadows cannot be on at the same time due to limits.

By the way, headlight shadows usually tank systems a lot because they weren't implemented properly in the first place, and it's highly advised to use Console Shadows, even if they introduce some bugs with shadows on damaged vehicles...

**Comment by SerGhost1915** [comment]
So. How can I resolve that? Wich archive I need to modify to get back the headlight shadows?.
Sorry for the unknowlegde of putting this issue on this list

**Comment by RecklessGlue540** [comment]
> So. How can I resolve that? Wich archive I need to modify to get back the headlight shadows?. Sorry for the unknowlegde of putting this issue on this list

It's in the graphics options, simply turn off Console Shadows. You don't need to modify anything else.
